theme: jekyll-theme-cayman
total: "1.152.224"
diario: "38.267"
obitos: "52.792"
obitosdiario: "1.374"
totalms: "1.145.906"
diarioms: "39.436"
obitosms: "52.645"
obitosdiarioms: "1.374"
dataref: "23/06/2020"
